services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7634
      MYSQL_DATABASE: timetableDB
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 7634

  backend:
    build: ./backend
    platform: linux/amd64
    container_name: backend
    volumes:
      - ./backend:/var/www/html/
    ports:
      - "8000:80"
    depends_on:
      - db

  frontend:
    image: httpd:latest
    platform: linux/amd64
    container_name: frontend
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    ports:
      - "3000:80"

volumes:
  mysql_data:
